version: '3.7'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/jsunwoo/data/wordpress
      o: bind                     
      type: none                         
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/jsunwoo/data/mariadb
      o: bind
      type: none

services:
  mariadb: #서비스 이름 
    container_name: my_mariadb
    build: ./requirements/mariadb/.  
    image: mariadb:42 #이미지 이름이 서비스 이름이랑 동일해야함. 
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
      - "443:443" #443포트로 접근가능한 유일한 입구 
    depends_on:
      - wordpress  
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:
    name: inception
    driver: bridge #TODO 고침
